apiVersion: v1
kind: PersistentVolume
metadata:
  name: crypto-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
  storageClassName: manual
